/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.conPlan.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ConPlanWebModule extends AbstractConPlanWebModule {
}
