/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.conPlan.ide


/**
 * Use this class to register ide components.
 */
class ConPlanIdeModule extends AbstractConPlanIdeModule {
}
